name: Update Factorio Version

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow every day at midnight
  workflow_dispatch:  # This allows the workflow to be manually triggered

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    #   - name: Fetch latest stable version
    #     id: fetch-version
    #     run: |
    #       VERSION=$(curl -s https://www.factorio.com/api/latest-releases | jq -r .stable.headless)
    #       echo "::set-output name=version::$VERSION"
      - name: Fetch latest stable version
        id: fetch-version
        run: |
            VERSION="1.0.0"
            echo "::set-output name=version::$VERSION"

      - name: Check and update Dockerfile
        id: update
        run: |
            CURRENT_VERSION=$(grep -oP '(?<=ARG version=").*(?=")' Dockerfile)
            if [ "$CURRENT_VERSION" != "${{ steps.fetch-version.outputs.version }}" ]; then
                sed -i 's/ARG version=".*"/ARG version="'${{ steps.fetch-version.outputs.version }}'"/' Dockerfile
                echo "::set-output name=updated::true"
            fi

      - name: Create new branch
        run: |
            git fetch origin
            git checkout main
            git checkout -b update-factorio-version-${{ steps.fetch-version.outputs.version }}
            git push -f origin update-factorio-version-${{ steps.fetch-version.outputs.version }}
            
      - name: Commit and push if Dockerfile was updated
        if: steps.update.outputs.updated == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Dockerfile
          git commit -m "Update Factorio version to ${{ steps.fetch-version.outputs.version }}"
          git push origin update-factorio-version-${{ steps.fetch-version.outputs.version }}

      - name: Create Pull Request
        if: steps.update.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
            title: "Update Factorio version to ${{ steps.fetch-version.outputs.version }}"
            branch: "update-factorio-version-${{ steps.fetch-version.outputs.version }}"
            base: "main"  # replace with your default branch if it's not "main"