name: Build & Push Production Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: [sonar]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}:latest
    - name: Build the second Docker image
      run: docker build . --file Dockerfile-GCP --tag ${{ secrets.DOCKER_REPO2 }}:latest
    - name: Login to Docker Repository
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
                
    - name: Run Snyk to check base (vanilla factorio) Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ secrets.DOCKER_REPO }}:latest
        args: --severity-threshold=critical --fail-on=all
      
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_REPO }}:latest
    - name: Push the second Docker image
      run: docker push ${{ secrets.DOCKER_REPO2 }}:latest

    - name: Deploy GCP image to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          cd /srv/factorio
          docker compose pull
          docker compose up -d

     - name: Install irssi
      run: sudo apt-get install -y irssi

    - name: Notify IRC Success
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        irssi -c ${{ secrets.IRC_SERVER }} -n github_actions \
        -channel '#${{ secrets.IRC_CHANNEL }}' -sendcmd "/msg #${{ secrets.IRC_CHANNEL }} Build of ${{ secrets.DOCKER_REPO }} & ${{ secrets.DOCKER_REPO2 }} completed successfully with commit message: $COMMIT_MSG; /quit"
      if: success()

    - name: Notify IRC Failure
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        irssi -c ${{ secrets.IRC_SERVER }} -n github_actions \
        -channel '#${{ secrets.IRC_CHANNEL }}' -sendcmd "/msg #${{ secrets.IRC_CHANNEL }} Build of ${{ secrets.DOCKER_REPO }} & ${{ secrets.DOCKER_REPO2 }} failed with commit message: $COMMIT_MSG; /quit"
      if: failure()